sudo: false
language: clojure
branches:
  only:
    - master
jdk:
  - oraclejdk8
jobs:
  include:
    - stage: test
      name: test
      script: lein test
    - script: lein eastwood
      name: lint
    # - stage: deploy
    #   name: deploy codox
    #   script: ./scripts/deploy_codox.sh
    # - script: ./scripts/deploy_clojars.sh
    #   name: deloy clojars
cache:
  timeout: 259200 # 3 days
  directories:
    - $HOME/.m2/repository
